### ISSUE TITLE
Error when no internet connection

### ISSUE THREAD

**Issue by joielechong** [spirosoik/RapidAndroidFramework#36]
I compile the project and it work when there is an internet connection, but when It disconnected from internet it crashed and show error "NullPointerException" in logcat.

FATAL EXCEPTION: main
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime: java.lang.RuntimeException: Could not dispatch event: class com.me.rapidapp.api.managers.events.common.NotInternetEvent to handler [EventHandler public void com.me.rapidapp.ui.common.AbstractFragmentActivity$ApiErrorHandler.onNoInternetEvent(com.me.rapidapp.api.managers.events.common.NotInternetEvent)]: null
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.dispatch(Bus.java:387)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.post(Bus.java:337)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.me.rapidapp.events.common.BusProvider$MainThreadBus$1.run(BusProvider.java:56)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4429)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:  Caused by: java.lang.NullPointerException
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.me.rapidapp.ui.common.AbstractFragmentActivity$ApiErrorHandler.onNoInternetEvent(AbstractFragmentActivity.java:693)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.dispatch(Bus.java:385)
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.squareup.otto.Bus.post(Bus.java:337)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.me.rapidapp.events.common.BusProvider$MainThreadBus$1.run(BusProvider.java:56)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4429)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)Â 
11-07 11:54:10.716 17503-17503/com.me.rapidapp E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)Â 
11-07 11:54:10.726 17503-17645/com.me.rapidapp W/Fabric: Received null settings, skipping initialization!
11-07 11:54:12.766 17503-17645/com.me.rapidapp I/dalvikvm: Could not find method retrofit.client.OkClient.openConnection, referenced from method com.twitter.sdk.android.core.DefaultClient$1.openConnection
11-07 11:54:12.766 17503-17645/com.me.rapidapp W/dalvikvm: VFY: unable to resolve virtual method 59104: Lretrofit/client/OkClient;.openConnection (Lretrofit/client/Request;)Ljava/net/HttpURLConnection;
11-07 11:54:12.766 17503-17645/com.me.rapidapp D/dalvikvm: VFY: replacing opcode 0x6f at 0x0002
11-07 11:59:10.777 17503-17503/com.me.rapidapp I/Process: Sending signal. PID: 17503 SIG: 9

**Comment by spirosoik** [comment]
@joielechong sorry for that. Fixed.

**Comment by joielechong** [comment]
Thank You :D
