### ISSUE TITLE
Error when Using Android Api 23

### ISSUE THREAD

**Issue by joielechong** [spirosoik/RapidAndroidFramework#38]

**Comment by spirosoik** [comment]
What's the problem. Could you send me the stacktrace?

The truth is not tested with Android Api 23.

**Comment by joielechong** [comment]
It happens when I upgrade all the dependencies to maximum API 23, all support library to 23, and build tools to 23.0.1.

I'll send you the stacktrace tonight.

**Comment by spirosoik** [comment]
@joielechong ok thanks, I will try it also.

**Comment by spirosoik** [comment]
@joielechong I fixed it, please pull the latest code and tell me if everything is OK.

**Comment by joielechong** [comment]
Still error on Device with API Level 15.
Here the log:
[error.txt](https://github.com/spirosoik/RapidAndroidFramework/files/36907/error.txt)

**Comment by spirosoik** [comment]
@joielechong ok I understood this is not related with the upgrade of API to 23, thit seems that is related with dagger! I will check. 

Did you add a new injected class which you haven't added into AppModule?

**Comment by joielechong** [comment]
@spirosoik: I don't add anything. It's freshly build from the latest code.

**Comment by spirosoik** [comment]
@joielechong I will check tomorrow, I am out of the office right now.

**Comment by joielechong** [comment]
@spirosoik: It turns out that on pre-Lollipop device we must add :
  compile 'com.android.support:multidex:1.0.1'

And extend BaseApplication with MultiDexApplication instead of Application.

source:
https://developer.android.com/tools/building/multidex.html https://developer.android.com/reference/android/support/multidex/MultiDexApplication.html

I send you a pr for fix this.

**Comment by spirosoik** [comment]
@joielechong sorry dude I was too busy these days. excellent! I will merge your PR

**Comment by joielechong** [comment]
@spirosoik: No problem, I just accidentally found the solution when learning your 'AndroidArchitecturePadawans'. 
Btw, Maybe we should include google play service by module not by the whole package.

Have a nice busy day too..;)

**Comment by spirosoik** [comment]
@joielechong yes this must be done but this code was developed when the packages are not released but we can do it. In this week I will publish the RxJedi repository

**Comment by joielechong** [comment]
@spirosoik: RxJedi! that's really the good news :D.
